-- MySQL Script generated by MySQL Workbench
-- Wed Oct 12 23:36:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laba_atm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laba_atm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laba_atm` DEFAULT CHARACTER SET utf8 ;
USE `laba_atm` ;

-- -----------------------------------------------------
-- Table `laba_atm`.`banks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`banks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`addresses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `house` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`cash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`cash` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `denomination` DECIMAL UNSIGNED NOT NULL,
  `quantity` DECIMAL UNSIGNED NOT NULL,
  `currency_type` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`atms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`atms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bank_id` BIGINT UNSIGNED NOT NULL,
  `address_id` BIGINT UNSIGNED NOT NULL,
  `cash_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atms_addresses_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_atms_banks1_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_atms_balance1_idx` (`cash_id` ASC) VISIBLE,
  CONSTRAINT `fk_atms_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `laba_atm`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atms_banks1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `laba_atm`.`banks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atms_balance1`
    FOREIGN KEY (`cash_id`)
    REFERENCES `laba_atm`.`cash` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`clients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `laba_atm`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`cards` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `number` BIGINT UNSIGNED NOT NULL,
  `pin` INT UNSIGNED NOT NULL,
  `balance` DECIMAL UNSIGNED NOT NULL,
  `currency_type` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_cards_accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `laba_atm`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`bank_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`bank_clients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bank_id` BIGINT UNSIGNED NOT NULL,
  `client_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_banks_has_clients_clients1_idx` (`client_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_banks_has_clients_banks1_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_banks_has_clients_banks1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `laba_atm`.`banks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_banks_has_clients_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `laba_atm`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba_atm`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba_atm`.`transactions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `atm_id` BIGINT UNSIGNED NOT NULL,
  `card_id` BIGINT UNSIGNED NOT NULL,
  `date_time` DATETIME NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `result` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_atms1_idx` (`atm_id` ASC) VISIBLE,
  INDEX `fk_transactions_cards1_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_atms1`
    FOREIGN KEY (`atm_id`)
    REFERENCES `laba_atm`.`atms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_cards1`
    FOREIGN KEY (`card_id`)
    REFERENCES `laba_atm`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
